set(_CATKIN_CURRENT_PACKAGE "panda_controllers")
set(panda_controllers_VERSION "1.0.0")
set(panda_controllers_MAINTAINER "George Jose Pollayil <georgejose.pollayil@phd.unipi.it>")
set(panda_controllers_PACKAGE_FORMAT "2")
set(panda_controllers_BUILD_DEPENDS "message_generation" "std_msgs" "eigen" "controller_interface" "dynamic_reconfigure" "franka_hw" "geometry_msgs" "franka_msgs" "hardware_interface" "libfranka" "pluginlib" "realtime_tools" "roscpp")
set(panda_controllers_BUILD_EXPORT_DEPENDS "message_runtime" "controller_interface" "dynamic_reconfigure" "franka_hw" "geometry_msgs" "franka_msgs" "hardware_interface" "libfranka" "pluginlib" "realtime_tools" "roscpp")
set(panda_controllers_BUILDTOOL_DEPENDS "catkin")
set(panda_controllers_BUILDTOOL_EXPORT_DEPENDS )
set(panda_controllers_EXEC_DEPENDS "franka_control" "franka_description" "message_runtime" "panda_moveit_config" "rospy" "controller_interface" "dynamic_reconfigure" "franka_hw" "geometry_msgs" "franka_msgs" "hardware_interface" "libfranka" "pluginlib" "realtime_tools" "roscpp")
set(panda_controllers_RUN_DEPENDS "franka_control" "franka_description" "message_runtime" "panda_moveit_config" "rospy" "controller_interface" "dynamic_reconfigure" "franka_hw" "geometry_msgs" "franka_msgs" "hardware_interface" "libfranka" "pluginlib" "realtime_tools" "roscpp")
set(panda_controllers_TEST_DEPENDS )
set(panda_controllers_DOC_DEPENDS )
set(panda_controllers_URL_WEBSITE "")
set(panda_controllers_URL_BUGTRACKER "https://github.com/CentroEPiaggio/panda_controllers/issues")
set(panda_controllers_URL_REPOSITORY "https://github.com/CentroEPiaggio/panda_controllers")
set(panda_controllers_DEPRECATED "")